export const SELECT_ENTRY = 'SELECT_ENTRY';
export const DESELECT_ENTRY = 'DESELECT_ENTRY';
export const DISPLAY_SEARCH_RESULTS = 'DISPLAY_SEARCH_RESULTS';
export const TOGGLE_TOP_SEARCHES = 'TOGGLE_TOP_SEARCHES';


